import Ad from 'Components/Ad';
import React from 'react';
import { Container } from './style';
interface Proptype {
  height: number | undefined;
}
const PRightBar: React.FC<Proptype> = ({ height }) => {
  return (
    <Container maxHeight={height}>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
      <Ad></Ad>
    </Container>
  );
};

export default PRightBar;
